frameworkVersion: ">=1.2.1"

service: gl-node-lite-object-detection

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: ca-central-1
  timeout: 30
  environment:
    TF_AWS_S3_MODEL_PATH: tensorflow/faster_rcnn_inception_v2_coco_2018_01_28/frozen_inference_graph.pb
    TF_AWS_MODEL_PROTOBUF_FILE_NAME: frozen_inference_graph.pb
    TF_AWS_S3_MODEL_BUCKET_NAME: grassland-models-00
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
      Resource:
        - "arn:aws:s3:::grassland-models-00"
        - "arn:aws:s3:::grassland-models-00/*"
        - "arn:aws:s3:::grassland-images"
        - "arn:aws:s3:::grassland-images/*"

functions:
  predict:
    handler: handler.predict
    memorySize: 3008
    events:
      - http:
          path: /predict
          method: get


package:
  exclude:
    - README.md
